AWSTemplateFormatVersion: "2010-09-09"
Description: Knowhere EC2 Stack CFT

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/jammy/stable/current/amd64/hvm/ebs-gp2/ami-id'
  UserdataS3BucketPath:
    Type: 'String'
    Default: '{{resolve:ssm:/gamehost/s3bucket/path/userdata:1}}'
  S3BucketArn:
    Type: 'String'
    Default: '{{resolve:ssm:/gamehost/s3bucket/arn:1}}'
  SSMPolicyArn:
    Type: 'String'
    Default: '{{resolve:ssm:/managedPolicyArns/ssmEC2Role:1}}'

Resources:
  knowhereIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'iam-knowhere-access'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref SSMPolicyArn
      Policies:
      - PolicyName: 'iam-knowhere-access-policy'
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:PutObject"
                - "s3:GetObject"
                - "s3:GetObjectVersion"
                - "s3:DeleteObject"
                - "s3:DeleteObjectVersion"
              Resource: !Sub '${S3BucketArn}/*'
            - Effect: Allow
              Action:
                - "ssm:DescribeParameters"
                - "ssm:GetParameters"
              Resource: "*"
            - Effect: Allow
              Action:
                - "kms:Decrypt"
                - "kms:Encrypt"
                - "kms:GenerateDataKey"
              Resource: "*"
  
  knowhereInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref knowhereIAMRole
  
  knowhereSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: "Knowhere EC2 Access"
            GroupDescription: "Allows specific traffic in/out for SSH and game servers"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 0.0.0.0/0
                Description: SSH
              - IpProtocol: tcp
                FromPort: 25565
                ToPort: 25565
                CidrIp: 0.0.0.0/0
                Description: Minecraft
              - IpProtocol: tcp
                FromPort: 8211
                ToPort: 8211
                CidrIp: 0.0.0.0/0
                Description: Palworld
  
  knowhereEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref knowhereInstanceProfile
      SecurityGroups:
        - !Ref knowhereSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt update
            apt install awscli -y
            aws s3 cp ${UserdataS3BucketPath} /opt/knowhere-userdata.sh
            chmod +x /opt/knowhere-userdata.sh
            bash /opt/knowhere-userdata.sh
      InstanceType: m5.large
      ImageId: !Ref LatestAmiId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: '30'
            DeleteOnTermination: 'true'
            Encrypted: 'true'
      Tags:
        - Key: Name
          Value: knowhere
  