name: Create release
on:
  push:
    branches: [ "main" ]
permissions:
      id-token: write
      contents: read
jobs:
  cut_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: "VERSION"
